// Generated by https://quicktype.io

export interface APIResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}

export interface pokInArray {
  data: Result;
  id: number;
  registered?: boolean;
}
